version: '3'

networks:
  nginx-php-node:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    networks:
      - nginx-php-node

  # php
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php-node

  # node
  node-service:
    image: node:latest
    container_name: node
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php-node